# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  setup:
    desc: setups the project for development
    cmds: 
      - pip install -r requirements-dev.txt
      - python install.py

  compile:
    desc: runs pip-compile for dev and prod
    cmds:
      - pip-compile --output-file requirements.txt pyproject.toml
      - pip-compile --extra=dev --output-file=requirements-dev.txt pyproject.toml

  run:
    desc: Run the main script
    cmds:
      - uvicorn main:app --reload

  sync:
    desc: Sync dependencies from venv to requirements.txt
    cmds:
      - pip-sync

  test:
    desc: Run tests
    cmds:
      - pytest tests -s

  lint:
    desc: runs linters and applies fixes
    cmds:
      - ruff format . 
      - ruff . --fix

  pr:
    desc: runs linters and checks for PR
    cmds:
      - python -m ruff format . --check
      - python -m ruff .
      - pytest tests
