# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

dotenv:
  - .env

tasks:
  stub:
    desc: stubs poetry version for python based on $PROJECT_PYTHON
    cmds:
      - poetry env use $PROJECT_PYTHON

  setup:
    desc: setups the project for development
    cmds:
      - task: stub
      - poetry install --with=dev --no-root --all-extras

  run:
    desc: Run the main script
    cmds:
      - uvicorn main:app --reload

  sync:
    desc: Sync dependencies from venv to requirements.txt
    cmds:
      - poetry install --with=dev --no-root --all-extras --sync

  test:
    desc: Run tests
    cmds:
      - pytest tests -s

  lint:
    desc: runs linters and applies fixes
    cmds:
      - ruff format .
      - ruff . --fix

  pr:
    desc: runs linters and checks for PR
    cmds:
      - python -m ruff format . --check
      - python -m ruff .
      - pytest tests
