name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: "Publish recipes-api"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Override __init__.py
        run: |
          echo "__version__ = \"${{ github.event.release.tag_name }}\"" > ./app/__init__.py

      - name: build release tagged the image
        permissions:
          contents: read
          packages: write
        run: |
          docker build --push --no-cache \
            --tag ghcr.io/hay-kot/recipes-api:latest \
            --tag ghcr.io/hay-kot/recipes-api:${{ github.event.release.tag_name }} \
            --build-arg="${{ github.sha }}" \
            --platform linux/amd64,linux/arm64 .
