name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  publish:
    name: "Publish recipes-api"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: login to container registry
        run: echo $CR_PAT docker login ghcr.io --username hay-kot --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: build release tagged the image
        if: ${{ inputs.release == true }}
        run: |
          docker build --push --no-cache \
            --tag ghcr.io/hay-kot/recipes-api:latest \
            --tag ghcr.io/hay-kot/recipes-api:${{ inputs.tag }} \
            --platform linux/amd64,linux/arm64 .
